baseURL: http://jason.gannon.me/
languageCode: en-us
title: Jason Gannon — Personal Site
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  copyright: "Copyright &copy; 2023 Jason Gannon --> All Rights Reserved."
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "The personal website of Jason Gannon — https://github.com/jasongannon/personal-site"
  keywords: [Blog, Portfolio, Technical Writing, Software Development]
  author: Jason Gannon
  mainSections:
    - posts
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  # disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  # ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  # disableSpecial1stPost: true
  disableScrollToTop: false
  # comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Jason Gannon"
    Content: "Developer, technical writer, avid traveler, cinephile, nice person,   \U0000270D" 

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/jasonmgannon/"
    - name: github
      url: "https://github.com/jasongannon"

  editPost:
    URL: "https://github.com/jasongannon/personal-site/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link    

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 1 
    - identifier: samples
      name: samples
      url: /samples/
      weight: 3
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 29
    - identifier: github
      name: github.com
      url: https://github.com/jasongannon/personal-site
      weight: 30
      external: true
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary    

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true        
