baseURL: https://jasongannon.me/
languageCode: en-us
title: Jason Gannon — Personal Site
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-E9BMMZKE0K

minify:
  disableXML: true
  minifyOutput: true

params:
  copyright: "Copyright &copy; 2023 Jason Gannon --> All Rights Reserved."
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "The personal website of Jason Gannon — https://github.com/jasongannon/personal-site"
  keywords: ["Technical Writing", "Software Development", "Developer Documentation", "Developer Experience"]
  author: Jason Gannon
  mainSections:
    - articles
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  # disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  # comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://jasongannon.me/static/favicons/favicon.ico"
    favicon16x16: "https://jasongannon.me/static/favicons/favicon-16x16.png"
    favicon32x32: "https://jasongannon.me/static/favicons/favicon-32x32.png"
    apple_touch_icon: "https://jasongannon.me/static/favicons/apple-touch-icon.png"
   # safari_pinned_tab: ""

  label:
    text: "Home"
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Jason Gannon"
    Content: "Developer, technical writer, traveler, filmgoer, music listener, coffee drinker,   \U0000270D" 

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/jasonmgannon/"
    - name: github
      url: "https://github.com/jasongannon"

  editPost:
    URL: "https://github.com/jasongannon/personal-site/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link    

  analytics:
    google:
      SiteVerificationTag: "G-E9BMMZKE0K"
    bing:
      SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 1 
    - identifier: articles
      name: articles
      url: /articles/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 29
    - identifier: github
      name: github.com
      url: https://github.com/jasongannon/personal-site
      weight: 30
      external: true
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary    

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true        
